dist: trusty
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: node_js
node_js:
  - "4"
  - "6"
  - "8"
env:
  - TEST_SUITE=unittests
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=browsers
    - node_js: "6"
      env: TEST_SUITE=demo

before_script:
  - npm install -g mocha-cli
  # Launch a virtual display imitation for Firefox
  - |
    case "$TEST_SUITE" in
      browsers )
        npm install -g karma-cli
        export DISPLAY=:99.0
        sh -e /etc/init.d/xvfb start
        sleep 3;;
    esac
script:
  - npm run-script lint
  - |
    case "$TEST_SUITE" in
      unittests ) npm test;;
      browsers ) npm run test-browser;;
      demo ) npm run test-demo;;
    esac
